services:
  nast:
    image: nats:latest
    ports:
      - "8222:8222"

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./apps/gateway/src:/usr/src/app/apps/gateway/src
    command: bun run dev
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
